@startuml
'https://plantuml.com/class-diagram

left to right direction
package Acciones{
usecase "Mostrar menú" as menu
usecase "Pedir comida" as pedir

}

:Cliente: -- menu
:Cliente: -- pedir
 (Entregar comida)-- :Restaurante:
 menu -- :Restaurante:
 
 left to right direction
:Cliente: -- (Confirmar pedido)
:Cliente: -- (Cancelar pedido)
(Confirmar pedido) --> (Devolver pedido) : <<include>>
(Cancelar pedido) --> (Devolver pedido) : <<include>>
(Acceder) <-- (Registrarse) : <<extend>>

(Pagar)<-- (Pagar con tarjeta)
(Pagar)<-- (Pagar en efectivo)

:Cliente: -- (Reservar vuelo)
:Cliente VIP: -- (Elegir asientos)

left to right direction
:Cliente: -- (Meter dinero)
:Cliente: -- (Pedir azucar)
:Cliente: -- (Pedir Producto)
:Cliente: -- (Cancelar)
(Cancelar) -->(Devolver dinero) : <<include>>
(Pedir Producto) --> (Devolver dinero) : <<include>>

left to right direction
:new Actor: -- (Identificarse)
:new Actor: -- (Pagar)
:new Actor: -- (elegir mensajero)
:new Actor: -- (Confirmar)
(Identificarse) <--(Registrarse) : <<extend>>
(Pagar) <-- (Pagar con tarjeta)
(Pagar) <-- (Pagar con transferencia)

:Ciudadano: -- (Registrar entrada)
:Ciudadano extranjero: -- (Tomar huellas)
(Tomar huellas) --> (Registrar entrada) : <<extend>>
:Ciudadano: <-- :Ciudadano extranjero:


@enduml
